<?php
namespace OnKupon\Agent;
class Installer {
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate(); $p=$wpdb->prefix; $sql=[];
 $sql[]="CREATE TABLE {$p}onkupon_agent_runs (id bigint unsigned NOT NULL AUTO_INCREMENT, run_uuid varchar(64) NOT NULL, run_type varchar(64) NOT NULL, status varchar(32) NOT NULL, started_at datetime NULL, finished_at datetime NULL, duration_ms bigint unsigned DEFAULT 0, items_processed int DEFAULT 0, items_published int DEFAULT 0, items_skipped int DEFAULT 0, error_count int DEFAULT 0, token_cost_estimate decimal(12,6) DEFAULT 0, notes text NULL, PRIMARY KEY (id), KEY run_uuid (run_uuid), KEY status (status)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_actions (id bigint unsigned NOT NULL AUTO_INCREMENT, action_uuid varchar(64) NOT NULL, run_uuid varchar(64) NULL, action_type varchar(64) NOT NULL, object_type varchar(64) NULL, object_id bigint unsigned DEFAULT 0, status varchar(32) NOT NULL, input_hash varchar(64) NULL, output_hash varchar(64) NULL, created_at datetime NOT NULL, completed_at datetime NULL, error_message text NULL, metadata_json longtext NULL, PRIMARY KEY (id), KEY action_uuid (action_uuid), KEY status (status)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_candidates (id bigint unsigned NOT NULL AUTO_INCREMENT, candidate_uuid varchar(64) NOT NULL, source_type varchar(64) NOT NULL, source_url text NULL, source_title text NULL, source_hash varchar(64) NOT NULL, related_product_ids_json text NULL, trend_score decimal(8,4) DEFAULT 0, commercial_score decimal(8,4) DEFAULT 0, freshness_score decimal(8,4) DEFAULT 0, duplicate_status varchar(32) DEFAULT 'new', status varchar(32) DEFAULT 'new', created_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id), UNIQUE KEY source_hash (source_hash)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_product_scores (id bigint unsigned NOT NULL AUTO_INCREMENT, product_id bigint unsigned NOT NULL, product_name text NULL, product_url text NULL, category_ids_json text NULL, product_status varchar(32) NULL, content_score decimal(8,4) DEFAULT 0, trend_score decimal(8,4) DEFAULT 0, revenue_score decimal(8,4) DEFAULT 0, freshness_score decimal(8,4) DEFAULT 0, last_content_at datetime NULL, last_social_at datetime NULL, updated_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id), UNIQUE KEY product_id (product_id)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_social_queue (id bigint unsigned NOT NULL AUTO_INCREMENT, social_uuid varchar(64) NOT NULL, post_id bigint unsigned DEFAULT 0, platform varchar(32) NOT NULL, account_id varchar(128) NULL, status varchar(32) NOT NULL, scheduled_at datetime NULL, published_at datetime NULL, remote_post_id varchar(191) NULL, remote_url text NULL, message text NOT NULL, media_ids_json text NULL, retry_count int DEFAULT 0, last_error text NULL, metrics_json longtext NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), KEY status (status), KEY platform (platform)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_metrics (id bigint unsigned NOT NULL AUTO_INCREMENT, object_type varchar(64) NOT NULL, object_id bigint unsigned DEFAULT 0, platform varchar(64) NULL, metric_name varchar(64) NOT NULL, metric_value decimal(18,6) DEFAULT 0, measured_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id), KEY object_metric (object_type,object_id,metric_name)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_learning_weights (id bigint unsigned NOT NULL AUTO_INCREMENT, dimension varchar(64) NOT NULL, variant_key varchar(128) NOT NULL, weight decimal(10,6) DEFAULT 1, impressions bigint unsigned DEFAULT 0, clicks bigint unsigned DEFAULT 0, conversions bigint unsigned DEFAULT 0, engagement_score decimal(10,6) DEFAULT 0, revenue_score decimal(12,6) DEFAULT 0, last_used_at datetime NULL, updated_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id), UNIQUE KEY dim_variant (dimension,variant_key)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_costs (id bigint unsigned NOT NULL AUTO_INCREMENT, run_uuid varchar(64) NULL, provider varchar(64) NOT NULL, model varchar(128) NULL, input_tokens int DEFAULT 0, output_tokens int DEFAULT 0, estimated_cost decimal(12,6) DEFAULT 0, created_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_logs (id bigint unsigned NOT NULL AUTO_INCREMENT, level varchar(20) NOT NULL, channel varchar(64) NOT NULL, message text NOT NULL, context_json longtext NULL, created_at datetime NOT NULL, PRIMARY KEY (id), KEY level_channel (level,channel)) $c";
 $sql[]="CREATE TABLE {$p}onkupon_agent_review_requests (id bigint unsigned NOT NULL AUTO_INCREMENT, order_id bigint unsigned NOT NULL, product_id bigint unsigned NOT NULL, customer_id bigint unsigned DEFAULT 0, customer_email_hash varchar(64) NOT NULL, status varchar(32) NOT NULL, request_count int DEFAULT 0, last_requested_at datetime NULL, review_id bigint unsigned DEFAULT 0, created_at datetime NOT NULL, metadata_json longtext NULL, PRIMARY KEY (id), KEY order_product (order_id,product_id)) $c";
  $sql[]="CREATE TABLE {$p}onkupon_agent_marketplace_programs (id bigint unsigned NOT NULL AUTO_INCREMENT, company_key varchar(191) NOT NULL, name varchar(255) NULL, category varchar(191) NULL, description longtext NULL, listing_url text NULL, logo_url text NULL, commission varchar(255) NULL, score decimal(6,2) NOT NULL DEFAULT 0, score_breakdown longtext NULL, decision varchar(32) NOT NULL DEFAULT 'pending', decision_reason text NULL, approval_token varchar(64) NOT NULL DEFAULT '', decided_at datetime NULL, applied_at datetime NULL, joined_at datetime NULL, first_seen_at datetime NULL, last_seen_at datetime NULL, PRIMARY KEY (id), UNIQUE KEY company_key (company_key), KEY decision (decision), KEY score (score)) $c";
 foreach($sql as $q){ dbDelta($q); } add_option('onkupon_agent_settings', Plugin::defaults(), '', false); \OnKupon\Agent\Migration\JsonPostMetaRepair::run(); ( new \OnKupon\Agent\Security\SecretsManager() )->migrate_legacy_social_oauth(); update_option('onkupon_agent_db_version', ONKUPON_AGENT_VERSION, false); }
}
